NAME_COL = 'Name'
AGE_COL = 'Age'
WORK_EXP_COL = 'Work Exp'
SEX_COL = 'Sex'
NEW_EMP_COL = 'New Employee'
VOCATION_DAYS_COL = 'Vocation Days'

GE_COLUMN = "column"
GE_MIN_VALUE = "min_value"
GE_STRICT_MIN = "strict_min"
GE_MAX_VALUE = "max_value"
GE_STRICT_MAX = "strict_max"
GE_OR_EQUAL = "or_equal"
GE_TYPE = "type_"
GE_VALUE_SET = "value_set"
GE_EXPECT_COLUMN_TO_EXIST = "expect_column_to_exist"
GE_EXPECT_COLUMN_VALUES_TO_BE_BETWEEN = "expect_column_values_to_be_between"
GE_EXPECT_COLUMN_DISTINCT_VALUES_TO_BE_IN_SET = "expect_column_distinct_values_to_be_in_set"
GE_EXPECT_COLUMN_VALUES_TO_NOT_BE_NULL = "expect_column_values_to_not_be_null"
GE_EXPECT_COLUMN_VALUES_TO_BE_OF_TYPE = "expect_column_values_to_be_of_type"